spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tokio
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_schema: api
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: tokio-crud-application

app:
  jwt:
    secret: pDUeQac7AWR2XB7KlUGK1qdRj6Ywkd5We678gGSHT5qazXCVBn3n0sP1MjLO9PQR
    expiration: 86400000  # 1 dia

via-cep:
  url: https://viacep.com.br/ws/